# Generated by Django 5.0.2 on 2024-02-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_student_progres'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='progres',
            field=models.CharField(blank=True, choices=[('high', 'high'), ('good', 'good'), ('medium', 'medium'), ('weak', 'weak')], max_length=50, null=True),
        ),
    ]
