# Generated by Django 5.0.2 on 2024-02-13 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_progres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='progres',
        ),
    ]
